version: '3'
services:
  broker:
    image: eclipse-mosquitto 
    container_name: "broker"
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      simulacion-net:
        ipv4_address: 172.16.240.10

  publisher:
    build: .
    container_name: "publisher"
    ports:
      - "1880:1880"
    networks:
      simulacion-net:
        ipv4_address: 172.16.240.20

  simulacion:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: "simulacion"
    links:
      - "broker"
    volumes:
      - .:/app
    ports:
      - "1881:1881"
    networks:
      simulacion-net:
        ipv4_address: 172.16.240.30

networks:
  simulacion-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.240.0/24
        
