from enum import Enum


class EventTypeEnum(Enum):

    CAMIONETA_REGRESA_A_BUSCAR_PEDIDO = 'CAMIONETA_REGRESA_A_BUSCAR_PEDIDO'
    ENTREGAR_PEDIDO = 'ENTREGAR_PEDIDO'
    ENVIAR_PEDIDO = 'ENVIAR_PEDIDO'
    LLAMO_CLIENTE = 'LLAMO_CLIENTE'
    PIZZA_VENCE = 'PIZZA_VENCE'
    CAMIONETA_REGRESA_VACIA = 'CAMIONETA_REGRESA_VACIA'
