from enum import Enum


class EventTypeEnum(Enum):

    CAMIONETA_REGRESA_A_RESTAURANTE = 'CAMIONETA_REGRESA_A_RESTAURANTE'
    ENTREGAR_PIZZA = 'ENTREGAR_PIZZA'
    ENVIAR_PEDIDO = 'ENVIAR_PEDIDO'
    LLAMO_CLIENTE = 'LLAMO_CLIENTE'
    PIZZA_VENCE = 'PIZZA_VENCE'
